version: '3.8'


services:
  mongo-db-test:
    image: mongo:8.0.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo-test:/data/db
    ports:
      - 27020:27017
  
  postgres-db-test:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data
    ports:
      - 5435:5432
